### ISSUE TITLE
cat 老师有 cocoapods-cat-bin 的源码吗?

### ISSUE THREAD

**Issue by BestiOSDev** [Cat1237/cocoapods-project-gen#3]
cat 老师有 cocoapods-cat-bin 的源码吗? 有的话能提供下吗

**Comment by Cat1237** [comment]
cocoapods-cat-bin 是用来干啥的了？我都给忘了。如果是二进制制作的话，应该就是这个[cocoapods-project-gen]项目。不过得调试下，改一改里面的东西

**Comment by Cat1237** [comment]
> cat 老师有 cocoapods-cat-bin 的源码吗? 有的话能提供下吗

cocoapods-cat-bin 是用来干啥的了？我都给忘了。如果是二进制制作的话，应该就是这个[cocoapods-project-gen]项目。不过得调试下，改一改里面的东西

**Comment by BestiOSDev** [comment]
我手上有一套 iOS 工程化实战班的课, 但是缺少资料和源码. 我想有偿求 Cat 老师的源码和资料 .
如果可以的话 加我 qq: 1060545231
